export const FETCH_STATS = "FETCH_STATS"
export const RECEIVE_STAT = "RECEIVE_STAT"
export const RECEIVE_STAT_FAIL = "RECEIVE_STAT_FAIL"
export const REQUEST_STAT = "REQUEST_STAT"

export const DISPLAY_DETAILED_STAT = "DISPLAY_DETAILED_STAT"